// src/app/api/videos/route.js

/**
 * GET /api/videos
 *
 * Returns list of all videos generated by the current user.
 * Used for "My Videos" library page.
 *
 * Flow:
 * 1. Get userId from request (TODO: Extract from JWT later)
 * 2. Query MongoDB for all user's videos
 * 3. Sort by creation date (newest first)
 * 4. Return array with video metadata
 *
 * Supports filtering and pagination (optional query params)
 */

import { NextResponse } from "next/server";
import { getUserVideos } from "@/lib/db";
import { getUserFromRequest } from "@/lib/auth";

export async function GET(request) {
  try {
    // Extract query parameters from URL
    const { searchParams } = new URL(request.url);

    // Optional: Filter by status
    const status = searchParams.get("status"); // "completed", "processing", "failed"

    // Optional: Pagination
    const limit = parseInt(searchParams.get("limit")) || 20;
    const page = parseInt(searchParams.get("page")) || 1;
    const userId = await getUserFromRequest();

    // ===== VALIDATION =====
    if (!userId) {
      return NextResponse.json(
        { error: "Unauthorized. Please login first." },
        { status: 401 }
      );
    }

    // ===== QUERY DATABASE =====
    // Get all videos for this user, sorted by newest first
    const videos = await getUserVideos(userId, limit);

    // ===== FILTER BY STATUS (Optional) =====
    let filteredVideos = videos;
    if (status) {
      filteredVideos = videos.filter((video) => video.status === status);
    }

    // ===== PROCESS VIDEOS =====
    // Add computed fields and clean up data
    const processedVideos = filteredVideos.map((video) => ({
      id: video._id.toString(),
      jobId: video.jobId,
      status: video.status,
      prompt: video.prompt,
      enhancedPrompt: video.enhancedPrompt,

      // Video URLs (null if not completed)
      videoUrl: video.videoUrl,
      thumbnailUrl: video.thumbnailUrl,

      // Settings
      duration: video.duration,
      aspectRatio: video.aspectRatio,

      // Progress (useful for showing in-progress videos)
      progress: video.progress,

      // Timestamps
      createdAt: video.createdAt,
      completedAt: video.completedAt,

      // Computed: How long ago was this created?
      timeAgo: getTimeAgo(video.createdAt),

      // Computed: Is this video ready?
      isReady: video.status === "completed",

      // Computed: Generation time (if completed)
      generationTime: video.completedAt
        ? Math.round(
            (new Date(video.completedAt) - new Date(video.createdAt)) / 1000
          )
        : null,
    }));

    // ===== GROUP BY STATUS (for UI convenience) =====
    const grouped = {
      processing: processedVideos.filter((v) => v.status === "processing"),
      completed: processedVideos.filter((v) => v.status === "completed"),
      failed: processedVideos.filter((v) => v.status === "failed"),
    };

    // ===== RETURN RESPONSE =====
    return NextResponse.json({
      success: true,
      total: processedVideos.length,
      videos: processedVideos,
      grouped, // Convenient for rendering different sections
      stats: {
        totalCompleted: grouped.completed.length,
        totalProcessing: grouped.processing.length,
        totalFailed: grouped.failed.length,
      },
    });
  } catch (error) {
    console.error("Get videos error:", error);

    return NextResponse.json(
      {
        error: "Failed to fetch videos",
        message: error.message,
      },
      { status: 500 }
    );
  }
}

// ===== HELPER FUNCTION =====

/**
 * Convert timestamp to human-readable "time ago" format
 * Example: "2 hours ago", "3 days ago"
 */
function getTimeAgo(timestamp) {
  const seconds = Math.floor((new Date() - new Date(timestamp)) / 1000);

  const intervals = {
    year: 31536000,
    month: 2592000,
    week: 604800,
    day: 86400,
    hour: 3600,
    minute: 60,
  };

  for (const [unit, secondsInUnit] of Object.entries(intervals)) {
    const interval = Math.floor(seconds / secondsInUnit);
    if (interval >= 1) {
      return `${interval} ${unit}${interval > 1 ? "s" : ""} ago`;
    }
  }

  return "Just now";
}
